units = [
    {
        "name": "Blue",
        "file": "blue.png",
        "resilience": 40,
        "speed": 160,
        "action_dice": 50,
        "p_bst": 0,
        "def_p": 0,
        "w_bst": 0,
    },
    {
        "name": "Red",
        "file": "red.png",
        "resilience": 50,
        "speed": 95,
        "action_dice": 50,
        "p_bst": 10,
        "def_p": 0,
        "w_bst": 0,
    },
    {
        "name": "Green",
        "file": "green.png",
        "resilience": 60,
        "speed": 70,
        "action_dice": 50,
        "p_bst": 10,
        "def_p": 10,
        "w_bst": 0,
    },
    {
        "name": "White",
        "file": "white.png",
        "resilience": 50,
        "speed": 75,
        "action_dice": 50,
        "p_bst": 0,
        "def_p": 0,
        "w_bst": 10,
    },
]
